[tool.poetry]
name = "html_summary"
version = "0.2.1"
description = ""
authors = ["narumi <toucans-cutouts0f@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.1.17"
langchain-openai = "^0.1.6"
langchain-text-splitters = "^0.0.1"
python-dotenv = "^1.0.1"
click = "^8.1.7"
loguru = "^0.7.2"
httpx = "^0.27.0"
beautifulsoup4 = "^4.12.3"
lxml = "^5.2.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-cov = "^4.1.0"
ruff = "^0.1.8"
toml = "^0.10.2"
mypy = "^1.8.0"


[tool.poetry.group.mypy.dependencies]
types-xmltodict = "^0.13.0.3"
lxml-stubs = "^0.5.1"
types-tqdm = "^4.66.0.20240417"
types-setuptools = "^69.5.0.20240519"
types-requests = "^2.31.0.20240406"
types-regex = "^2024.5.15.20240519"
types-pyyaml = "^6.0.12.20240311"
types-pytz = "^2024.1.0.20240417"
types-pymysql = "^1.1.0.20240425"
types-psycopg2 = "^2.9.21.20240417"
types-psutil = "^5.9.5.20240516"
types-protobuf = "^5.26.0.20240422"
types-pillow = "^10.2.0.20240511"
types-html5lib = "^1.1.11.20240228"
types-hdbcli = "^2.20.0.20240418"
types-docutils = "^0.21.0.20240423"
rpds-py = "^0.18.1"
pycparser = "^2.22"
types-pygments = "^2.18.0.20240506"
types-cffi = "^1.16.0.20240331"
types-beautifulsoup4 = "^4.12.0.20240511"
referencing = "^0.35.1"
pandas-stubs = "^2.2.2.240514"
cffi = "^1.16.0"
types-jsonschema = "^4.22.0.20240501"
cryptography = "^42.0.7"
types-pyopenssl = "^24.1.0.20240425"
types-redis = "^4.6.0.20240425"

[tool.poetry.scripts]
html-summary = "html_summary.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = ["build"]
line-length = 120

[tool.ruff.lint]
select = [
    "B",   # flake8-bugbear
    "C",   # flake8-comprehensions
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
    "W",   # pycodestyle warnings
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.ruff.lint.isort]
force-single-line = true

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
